### PR TITLE
fix: zip64 central header (issue 617)

### LINKED ISSUE #617: Zipfile >4GB with complex dir tree is created incorrectly
A zipfile whose contents exceeds 4GB and has a fairly complex tree, is incorrectly created.

The example program https://github.com/zip-rs/zip2/blob/master/examples/write_dir.rs and **version 7.2.0** running on **linux** was used to test this. Also, none of the files are greater than 4GB.

If you do not add the directories:
```rust
zip.add_directory(path_as_string, options)?;
```
then the zip file is correct.

Using zipdetails on the incorrect zipfile you have these errors:
```
WARNING!                                                                                                                               
Zip local header not found at offset 0x17D                                                                                             
Skipping 0x13eaed8e6 bytes to Central Directory...   

...

CENTRAL HEADER ref Local #2C: 'b803dca6-5fbc-57aa-be7f-cdf25bc43471/SUBDIR2/SUBSUBDIR_FILES/' matches with CENTRAL HEADER ref Local #1: 'b803dca6-5fbc-57aa-be7f-cdf25bc43471/'
                                                                                                                                       
                                                                                                                                       
Unexpected END at offset 13EAEEDB1, value 00000001
                                                                                                                                       
WARNINGS                                                                                                                               
                                                                   
* Expected Zip header not found at offset 0x17D, skipped 0x13EAED8E6 bytes                                                             
                                                                                                                                       
* 1 duplicate entries
```

If I remove some of the files to make the zipfile less than 4GB, the zipfile is correct.

### PR DESCRIPTION
**Pull request by Its-Just-Nans**
Fix #617

Currenlty there is also two extra field, that's not correct I think

```
125C00A50 CENTRAL HEADER #13    02014B50 (33639248)
125C00A54 Created Zip Spec      2D (45) '4.5'
125C00A55 Created OS            03 (3) 'Unix'
125C00A56 Extract Zip Spec      2D (45) '4.5'
125C00A57 Extract OS            00 (0) 'MS-DOS'
125C00A58 General Purpose Flag  0000 (0)
125C00A5A Compression Method    0000 (0) 'Stored'
125C00A5C Modification Time     5C461814 (1548097556) 'Thu Feb  5 20:00:40 2026'
125C00A60 CRC                   540AD08C (1409994892)
125C00A64 Compressed Size       FFFFFFFF (4294967295)
125C00A68 Uncompressed Size     FFFFFFFF (4294967295)
125C00A6C Filename Length       003C (60)
125C00A6E Extra Length          0038 (56)
125C00A70 Comment Length        0000 (0)
125C00A72 Disk Start            0000 (0)
125C00A74 Int File Attributes   0000 (0)
          [Bit 0]               0 'Binary Data'
125C00A76 Ext File Attributes   81ED0000 (2179792896)
          [Bits 16-24]          01ED (493) 'Unix attrib: rwxr-xr-x'
          [Bits 28-31]          08 (8) 'Regular File'
125C00A7A Local Header Offset   FFFFFFFF (4294967295)
125C00A7E Filename              'b803dca6-5fbc-57aa-be7f-cdf25bc43471/SUBDIR2/random_5M_9.bin'
125C00ABA Extra ID #1           0001 (1) 'ZIP64'
125C00ABC   Length              0018 (24)
125C00ABE   Uncompressed Size   00000000FFFFFFFF (4294967295)
125C00AC6   Compressed Size     00000000FFFFFFFF (4294967295)
125C00ACE   Offset to Local Dir 000000010680042A (4404020266)
125C00AD6 Extra ID #2           0001 (1) 'ZIP64'
125C00AD8   Length              0018 (24)
125C00ADA   Uncompressed Size   000000001F400000 (524288000)
125C00AE2   Compressed Size     000000001F400000 (524288000)
125C00AEA   Offset to Local Dir 000000010680042A (4404020266)
```

### CODE REVIEW

**Comment by Its-Just-Nans** [comment]
This MR is incorrect

```
 The order of the fields in the zip64 extended 
      information record is fixed, but the fields MUST
      only appear if the corresponding Local or Central
      directory record field is set to 0xFFFF or 0xFFFFFFFF.
```

**Comment by Its-Just-Nans** [comment]
I think we should wait on https://github.com/pmqs/zipdetails/pull/28

If it's merged, we should then be able to remove the code < line 1000 in `types.rs` (like `is_zip_64`)

**Comment by Its-Just-Nans** [comment]
Amazon AI is correct but our current implementation is not



This MR needs work and testing

Also, we will need to think about large_file option which is causing our implementation to be incorrect

**Comment by pmqs** [comment]
> Fix #617
> 
> Currenlty there is also two extra field, that's not correct I think
> 
> ```
> 125C00A50 CENTRAL HEADER #13    02014B50 (33639248)
> 125C00A54 Created Zip Spec      2D (45) '4.5'
> 125C00A55 Created OS            03 (3) 'Unix'
> 125C00A56 Extract Zip Spec      2D (45) '4.5'
> 125C00A57 Extract OS            00 (0) 'MS-DOS'
> 125C00A58 General Purpose Flag  0000 (0)
> 125C00A5A Compression Method    0000 (0) 'Stored'
> 125C00A5C Modification Time     5C461814 (1548097556) 'Thu Feb  5 20:00:40 2026'
> 125C00A60 CRC                   540AD08C (1409994892)
> 125C00A64 Compressed Size       FFFFFFFF (4294967295)
> 125C00A68 Uncompressed Size     FFFFFFFF (4294967295)
> 125C00A6C Filename Length       003C (60)
> 125C00A6E Extra Length          0038 (56)
> 125C00A70 Comment Length        0000 (0)
> 125C00A72 Disk Start            0000 (0)
> 125C00A74 Int File Attributes   0000 (0)
>           [Bit 0]               0 'Binary Data'
> 125C00A76 Ext File Attributes   81ED0000 (2179792896)
>           [Bits 16-24]          01ED (493) 'Unix attrib: rwxr-xr-x'
>           [Bits 28-31]          08 (8) 'Regular File'
> 125C00A7A Local Header Offset   FFFFFFFF (4294967295)
> 125C00A7E Filename              'b803dca6-5fbc-57aa-be7f-cdf25bc43471/SUBDIR2/random_5M_9.bin'
> 125C00ABA Extra ID #1           0001 (1) 'ZIP64'
> 125C00ABC   Length              0018 (24)
> 125C00ABE   Uncompressed Size   00000000FFFFFFFF (4294967295)
> 125C00AC6   Compressed Size     00000000FFFFFFFF (4294967295)
> 125C00ACE   Offset to Local Dir 000000010680042A (4404020266)
> 125C00AD6 Extra ID #2           0001 (1) 'ZIP64'
> 125C00AD8   Length              0018 (24)
> 125C00ADA   Uncompressed Size   000000001F400000 (524288000)
> 125C00AE2   Compressed Size     000000001F400000 (524288000)
> 125C00AEA   Offset to Local Dir 000000010680042A (4404020266)
> ```
Two ZIP64 extra fields is wrong. You only want one.

The second one looks ok. The first is corrupt

**Comment by Its-Just-Nans** [comment]
@Pr0methean 

https://github.com/zip-rs/zip2/blob/5fca23d26bbea7e47a99d5ef5ffc1d82eb901930/src/write.rs#L977-L982

What's the reason of this code ?

Are you sure about `Files that start on or past the 4GiB boundary are always ZIP64` ?

**Comment by Pr0methean** [comment]
Well, if they reach 4GiB compressed size before the EOCD is written, then they have to be so that the EOCD offset can be written.

**Comment by Its-Just-Nans** [comment]
> Well, if they reach 4GiB compressed size before the EOCD is written, then they have to be so that the EOCD offset can be written.

On the zip64 attributes some can be optionnal

In a case of a small file, placed inside the Zip file over 4GiB, only the `local_offset` needs to be in the zip64 attributes.

But `large_file` is forcing the compressed size and uncompressed size to be in the zip64 attributes
- https://github.com/zip-rs/zip2/blob/5fca23d26bbea7e47a99d5ef5ffc1d82eb901930/src/types.rs#L1179
- https://github.com/zip-rs/zip2/blob/5fca23d26bbea7e47a99d5ef5ffc1d82eb901930/src/types.rs#L1185

**Comment by Pr0methean** [comment]
@Its-Just-Nans When do you expect to have this ready to review and merge?

**Comment by Pr0methean** [comment]
/q The following tests are failing with "assertion failed: file_end >= self.stats.start":

    write::test::fuzz_crash_2024_07_17
    write::test::fuzz_crash_2024_07_19a
    write::test::test_fuzz_crash_2024_06_14
    write::test::test_fuzz_crash_2024_06_14b
    write::test::test_fuzz_crash_2024_06_14c
    write::test::test_fuzz_crash_2024_06_17
    write::test::test_fuzz_crash_2024_06_18b
    write::test::test_fuzz_failure_2024_05_08

Fix them. Do not include "[skip ci]" in the commit message, because we need CI to run to verify that the tests are fixed.

**Comment by Pr0methean** [comment]
@Its-Just-Nans The AI seems to be stuck in a loop trying to fix this PR: every attempted fix breaks the build, and every fix for the build errors reintroduces the bug.

File: tests/zip64_large.rs [hunk 1]
```diff
@@ -209,3 +215,117 @@ fn zip64_large() {
...
+        eprintln!("RAW ACCESS: {:x?}", raw_access);
+        assert_eq!(raw_access[0..4], [0x50, 0x4b, 0x03, 0x04]); // local file header signature
+        assert_eq!(raw_access[4..6], [0x2d, 0x00]); // version needed to extract
+        assert_eq!(raw_access[6..8], [0x00, 0x00]); // general purpose bit flag
+        assert_eq!(raw_access[8..10], [0x00, 0x00]); // compression method
+        // assert_eq!(raw_access[10..12], [0x00, 0x00]); // last mod file time
+        // assert_eq!(raw_access[12..14], [0x00, 0x00]); // last mod file date
+        assert_eq!(raw_access[14..18], [0x00, 0x00, 0x00, 0x00]); // crc-32
+        assert_eq!(raw_access[18..22], [0x00, 0x00, 0x00, 0x00]); // compressed size - IMPORTANT
+        assert_eq!(raw_access[22..26], [0x00, 0x00, 0x00, 0x00]); // uncompressed size - IMPORTANT
```
Comment (Its-Just-Nans) [inline tests/zip64_large.rs]: Both the size are set to 0xFFFFFFFF which for me seems incorrect

They should be set to 0x00000000

File: tests/zip64_large.rs [hunk 2]
```diff
@@ -209,3 +215,117 @@ fn zip64_large() {
...
+        eprintln!("RAW ACCESS: {:x?}", raw_access);
+        assert_eq!(raw_access[0..4], [0x50, 0x4b, 0x03, 0x04]); // local file header signature
+        assert_eq!(raw_access[4..6], [0x2d, 0x00]); // version needed to extract
+        assert_eq!(raw_access[6..8], [0x00, 0x00]); // general purpose bit flag
+        assert_eq!(raw_access[8..10], [0x00, 0x00]); // compression method
+        // assert_eq!(raw_access[10..12], [0x00, 0x00]); // last mod file time
+        // assert_eq!(raw_access[12..14], [0x00, 0x00]); // last mod file date
+        assert_eq!(raw_access[14..18], [176, 194, 100, 91]); // crc-32
+        assert_eq!(raw_access[18..22], [0xff, 0xff, 0xff, 0xff]); // compressed size
+        assert_eq!(raw_access[22..26], [0xff, 0xff, 0xff, 0xff]); // uncompressed size
```
Comment (Its-Just-Nans) [inline tests/zip64_large.rs]: same here

File: tests/zip64_large.rs (hunk 1 above)
Comment (Its-Just-Nans) [reply tests/zip64_large.rs]: Because right now, they are set to `0xFFFFFFFF` but there are NOT in the zip64 extra field

File: tests/zip64_large.rs (hunk 2 above)
Comment (Its-Just-Nans) [reply tests/zip64_large.rs]: Because right now, they are set to `0xFFFFFFFF` but there are NOT in the zip64 extra field

**Comment by Its-Just-Nans** [comment]
This happen when a file is added but it's not large enough to have the sizeS in extra field, but needs a offset field

Either we can
- force adding the size when it's `large_file` - and have a 2 + 2 + 3*8 long extra field - even if it's not needed
- don't add the size but only the offset and have a 2+2+8 long extra field

We also need to add a to the test a check on the central header field, one of the related issue is that when we override the lenght (see below), but this length is needed for the central header !

https://github.com/zip-rs/zip2/blob/2d836ad5d948827268499f8e46df029b1e883325/src/write.rs#L2267-L2268

**Comment by Pr0methean** [comment]
My understanding is that the size is expected to only be in the ZIP64 field when it's 0xFFFFFFFF in the main field.

**Comment by Its-Just-Nans** [comment]
> My understanding is that the size is expected to only be in the ZIP64 field when it's 0xFFFFFFFF in the main field.

yes correct

But the question is more "when do we set the size to `0xFFFFFFFF` ?"
Only when the file size if greater than `0xFFFFFFFF` ? Or also when the archive is large ?

**Comment by Pr0methean** [comment]
I think that's beyond my knowledge of the format.

**Comment by Its-Just-Nans** [comment]
Looking at the result of `zip` command

```
# force the order
zip -r archivename.zip ziptest/b803dca6-5fbc-57aa-be7f-cdf25bc43471/SUBDIR2/  ziptest/b803dca6-5fbc-57aa-be7f-cdf25bc43471/SUBDIR1/ -0
```

Inspect the zip

```
zipdetails archivename.zip

125C00D35 CENTRAL HEADER #D     02014B50
..........
125C00D49 Compressed Length     00000000
125C00D4D Uncompressed Length   00000000
..........
125C00D5F Local Header Offset   FFFFFFFF
125C00D63 Filename              'ziptest/b803dca6-5fbc-57aa-be7f-cdf25bc43471/SUBDIR1/SUBSUBDIR2/'
..........
125C00DBB Extra ID #0003        0001 'ZIP64'
125C00DBD   Length              0008
125C00DBF   Offset to Local Dir 00000001194005C6

125C00DC7 CENTRAL HEADER #E     02014B50
..........
125C00DDB Compressed Length     0C800000
125C00DDF Uncompressed Length   0C800000
..........
125C00DF1 Local Header Offset   FFFFFFFF
125C00DF5 Filename              'ziptest/b803dca6-5fbc-57aa-be7f-cdf25bc43471/SUBDIR1/SUBSUBDIR2/random_2M.bin'
..........
125C00E5A Extra ID #0003        0001 'ZIP64'
125C00E5C   Length              0008
125C00E5E   Offset to Local Dir 0000000119400640
```

So it seems that we should NOT force the large_file

Also @Pr0methean Do you know what is the utility of `large_file` option ?
Since we can detect it no ?

**Comment by Pr0methean** [comment]
If we detect it after 4 GiB has already been written, then we'd have to shift that 4 GiB over to make room for the extra local header that we didn't write initially (assuming that was even possible; the raw writer doesn't always implement `Seek`). That's why we have it.

**Comment by Pr0methean** [comment]
@Its-Just-Nans When do you expect to finish this? Because I'd like to release 8.2.0 in the next few days, with or without it.

**Comment by Its-Just-Nans** [comment]
> @Its-Just-Nans When do you expect to finish this? Because I'd like to release 8.2.0 in the next few days, with or without it.

Unfortunatly, I think it's going to take more time.
Also possibly breaking change (I'm trying not - but need to think about it)

**Review by Pr0methean — APPROVED** [review]
